package fr.mcstudio.enums;

public enum AnimationType {
    BOAT_SUMMON, DOLPHIN_SUMMON, SEASNAKE_ATTACK, SHARK_ATTACK, SHARK_COUNTER, SHARK_SUMMON, VOLCANO, WHALE_ATTACK, WHALE_COUNTER, WHALE_SUMMON, WHIRLPOOL, WIND
}
